<?php

namespace TMG\Api\ApiBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * AnalyticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyticRepository extends EntityRepository
{
    /**
     * Get the most recent date that exists in the table
     * and return as a DateTime object
     *
     * @return \DateTime
     */
    public function getMostRecentDate()
    {
        try {
            $result = new \DateTime(
                $this->createQueryBuilder('c')
                    ->select('c.reportDate')
                    ->orderBy('c.reportDate', 'DESC')
                    ->setMaxResults('1')
                    ->getQuery()
                    ->getSingleScalarResult()
            );
        } catch (NoResultException $e) {
            $result = new \DateTime('January 1, 2013');
        }
        
        return $result;
    }
}
