<?php

namespace TMG\Api\ApiBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductTypesRepository extends EntityRepository
{

    public function getIdByType($type)
    {
        return $this->createQueryBuilder('p')
            ->select('p.id')
            ->where('p.type = :type')
            ->setParameter('type', $type)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
