<?php

namespace TMG\Api\ApiBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use TMG\Api\ApiBundle\Entity\TripStayWinData;

/**
 * RateOurStaySubdomainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RateOurStaySubdomainRepository extends EntityRepository
{
}
