<?php

namespace TMG\Api\ApiBundle\Entity\Repository;

use Doctrine\ORM\QueryBuilder;

/**
 * ReputationCompetitorDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReputationCompetitorDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTotalsByDate($id, $start = null)
    {
        if (!$start) {
            $start = date('ym', strtotime('now'));
        }

        return $this->createQueryBuilder('rcd')
            ->select(
                'rcd.reviews',
                'rcd.rating',
                'rc.name',
                'rc.id'
            )
            ->join('rcd.competitor', 'rc')
            ->join('rc.reputation', 'r')
            ->where('r.property = :id')
            ->andWhere('rcd.yrmo = :start')
            ->setParameter('id', $id)
            ->setParameter('start', $start)
            ->groupBy('rc.name, rcd.site')
            ->getQuery()
            ->getResult();
    }

    public function getAllSiteDataByCompetitor($id, $start = null)
    {
        if (!$start) {
            $start = date('ym', strtotime('now'));
        }

        /** @var QueryBuilder $qb */
        $qb = $this->createQueryBuilder('rcd')
            ->select(
                'rcd.reviews',
                'rcd.rating',
                's.name',
                's.id',
                'rcd.url',
                'rcd.rssId',
                'rcd.monthTotal',
                'rcd.cityRank'
            )
            ->join('rcd.competitor', 'rc')
            ->join('rcd.site', 's')
            ->where('rcd.competitor = :id')
            ->andWhere('rcd.yrmo = :start')
            ->setParameter('id', $id)
            ->setParameter('start', $start)
            ->groupBy('rcd.site');

        return $qb->getQuery()->getResult();
    }
}
