<?php

namespace TMG\Api\ApiBundle\Entity\Repository;

/**
 * ReputationSiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReputationSiteRepository extends \Doctrine\ORM\EntityRepository
{
}
