<?php

namespace TMG\Api\ApiBundle\Entity\Repository;

/**
 * ReputationDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReputationDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTotalsByDate($id, $start)
    {
        $yrmo = new \DateTime($start);
        $yrmo = (int) $yrmo->format('ym');

        $total = $this->createQueryBuilder('rd')
            ->select(
                'SUM(rd.externalTotal) AS reviews',
                'AVG(rd.externalAverageRating) AS avg_rating',
                'AVG(rd.tripAdvisorRating) AS trip_rating',
                'SUM(rd.externalPositive) AS positive',
                'r.tripAdvisorRank AS trip_rank'
            )
            ->join('rd.reputation', 'r')
            ->where('r.property = :id')
            ->setParameter('id', $id)
            ->andWhere('rd.yrmo >= :yrmo')
            ->andWhere('rd.yrmo IS NOT NULL')
            ->setParameter('yrmo', $yrmo)
            ->getQuery()
            ->getResult();

        return $total;
    }

    public function findTotalByPropertyAndYrmo($id, $yrmo)
    {
        $total = $this->createQueryBuilder('rd')
            ->select('rd.externalTotal')
            ->join('rd.reputation', 'r')
            ->where('r.property = :id')
            ->setParameter('id', $id)
            ->andWhere('rd.yrmo = :yrmo')
            ->setParameter('yrmo', $yrmo)
            ->orderBy('rd.externalTotal', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult();

        return $total;
    }
}
