<?php

namespace TMG\Api\ApiBundle\Entity;

/**
 * ReputationQuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReputationQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
