<?php

namespace TMG\Api\ApiBundle\Entity\Repository;

/**
 * ReputationSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReputationSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
