<?php

namespace TMG\Api\ApiBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialRepository extends EntityRepository
{
    public function activeSocial($id)
    {
        return $this->createQueryBuilder('r')
            ->select('r.active')
            ->where('r.property = :id')
            ->andWhere('r.active IS NOT NULL')
            ->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
