<?php

namespace TMG\Api\ApiBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TollFreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TollFreeRepository extends EntityRepository
{
    public function activeTollFree($id)
    {
        return $this->createQueryBuilder('r')
            ->select('COUNT(r.id)')
            ->where('r.property = :id')
            ->andWhere('r.active IS NOT NULL')
            ->andWhere('r.active != 0')
            ->setParameter('id', $id)
            ->getQuery()
            ->getSingleScalarResult();
    }
}
