<?php

namespace TMG\Api\ApiBundle\Entity;

/**
 * TripsStayWinDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TripStayWinDataRepository extends \Doctrine\ORM\EntityRepository
{
}
