tmg_api_o_auth:
    resource: "@TMGApiOAuthBundle/Resources/config/routing.yml"
    prefix:   /

#REST
tmg_rest_api :
    type : rest
    resource : "routing_rest.yml"
    prefix : /api
    defaults:
        _format: json

api_dashboard:
    resource: "@ApiDashboardBundle/Resources/config/routing.yml"
    prefix:   /dashboard

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api

api_user:
    resource: "@ApiUserBundle/Resources/config/routing.yml"

api_global:
    resource: "@ApiGlobalBundle/Resources/config/routing.yml"

api_docs:
    resource: "@ApiDocsBundle/Resources/config/routing.yml"

# FOS OAuth Server
# ================

fos_oauth_server_token:
    path: /token
    defaults: { _controller: fos_oauth_server.controller.token:tokenAction, _method: [ GET, POST ]}

fos_oauth_server_authorize:
    path: /auth
    defaults: { _controller: FOSOAuthServerBundle:Authorize:authorize, _method: [ GET, POST ]}

# FOS Security
# ============
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_login:
    path: /login
    defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }

fos_user_security_check:
    path: /login_check
    defaults:  { _controller: FOSUserBundle:Security:check, _method: POST }

fos_user_security_logout:
    path: /logout
    defaults:  { _controller: FOSUserBundle:Security:logout, _method: POST }

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

# FOS Register
# ============
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_registration_register:
    path:      /register
    defaults:  { _controller: FOSUserBundle:Registration:register }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
