<?php

namespace TMG\Api\DocsBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ApiDocMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiDocMetaRepository extends EntityRepository
{
}
